name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Executing deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SRV_HOST }}
          username: ${{ secrets.SRV_USERNAME }}
          password: ${{ secrets.SRV_PASSWORD }}
          port: ${{ secrets.SRV_PORT }}
          script: |
            cd ~/discord-bot
            rm -rf kata-family-discord-bot
            git clone https://github.com/kzfor/kata-family-discord-bot.git --branch ${{ github.ref_name }}
            cd kata-family-discord-bot
            chmod +x ./gradlew
            ./gradlew build
            shopt -s extglob
            mv build/libs/bot-!(*plain*).jar ../target/discord-bot.jar
            chmod +x ../target/discord-bot.jar
            sudo systemctl restart discord-bot
      - name: Healthcheck
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: http://62.109.21.7:8888/actuator/health